### PR TITLE
Update 2021-06-03

### PR DESCRIPTION
**Pull request by jaguillette**
Updated plugin info and cache. The names of some plugins have changed to reflect their names in Omeka's plugin repository, so this change will require an update to atg-ops-oaas.

### CODE REVIEW

**Comment by jaguillette** [comment]
None of the files in the cache directory need review, as they're just pulled from the plugins themselves (so no need to view all 592 changed files, just the first 3

**Review by arthurian — APPROVED** [review]
Looks good! I reviewed the first 3 files as suggested. The testing notes on the plugins are great. :+1:

**Review by dodget — APPROVED** [review]
Looks good, thanks Jeremy

**Review by Tanvez — APPROVED** [review]
LGTM!

**Pull request merged**
